# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .team_entra_component import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azure-data-team-entra",
  "mod": "index",
  "fqn": "pulumi_demos_azure_data_team_entra",
  "classes": {
   "azure-data-team-entra:index:TeamEntraComponent": "TeamEntraComponent"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azure-data-team-entra",
  "token": "pulumi:providers:azure-data-team-entra",
  "fqn": "pulumi_demos_azure_data_team_entra",
  "class": "Provider"
 }
]
"""
)
