# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = ['TeamEntraComponentArgs', 'TeamEntraComponent']

@pulumi.input_type
class TeamEntraComponentArgs:
    def __init__(__self__, *,
                 team_name: pulumi.Input[_builtins.str],
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 password_rotation_days: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TeamEntraComponent resource.
        """
        pulumi.set(__self__, "team_name", team_name)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if owners is not None:
            pulumi.set(__self__, "owners", owners)
        if password_rotation_days is not None:
            pulumi.set(__self__, "password_rotation_days", password_rotation_days)

    @_builtins.property
    @pulumi.getter(name="teamName")
    def team_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "team_name")

    @team_name.setter
    def team_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "team_name", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter
    def owners(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "owners")

    @owners.setter
    def owners(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "owners", value)

    @_builtins.property
    @pulumi.getter(name="passwordRotationDays")
    def password_rotation_days(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "password_rotation_days")

    @password_rotation_days.setter
    def password_rotation_days(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_rotation_days", value)


@pulumi.type_token("azure-data-team-entra:index:TeamEntraComponent")
class TeamEntraComponent(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 password_rotation_days: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a TeamEntraComponent resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TeamEntraComponentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a TeamEntraComponent resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param TeamEntraComponentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TeamEntraComponentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 password_rotation_days: Optional[pulumi.Input[_builtins.str]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TeamEntraComponentArgs.__new__(TeamEntraComponentArgs)

            __props__.__dict__["environment"] = environment
            __props__.__dict__["owners"] = owners
            __props__.__dict__["password_rotation_days"] = password_rotation_days
            if team_name is None and not opts.urn:
                raise TypeError("Missing required property 'team_name'")
            __props__.__dict__["team_name"] = team_name
            __props__.__dict__["application_id"] = None
            __props__.__dict__["client_id"] = None
            __props__.__dict__["identity_config"] = None
            __props__.__dict__["service_principal_id"] = None
            __props__.__dict__["service_principal_password"] = None
        super(TeamEntraComponent, __self__).__init__(
            'azure-data-team-entra:index:TeamEntraComponent',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="applicationId")
    def application_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "application_id")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="identityConfig")
    def identity_config(self) -> pulumi.Output['outputs.EntraIdentityConfig']:
        return pulumi.get(self, "identity_config")

    @_builtins.property
    @pulumi.getter(name="servicePrincipalId")
    def service_principal_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "service_principal_id")

    @_builtins.property
    @pulumi.getter(name="servicePrincipalPassword")
    def service_principal_password(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "service_principal_password")

