# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .databricks_workspace_component import *
from .provider import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pulumi-resource-databricks-workspace",
  "mod": "index",
  "fqn": "pulumi_demos_pulumi_resource_databricks_workspace",
  "classes": {
   "pulumi-resource-databricks-workspace:index:DatabricksWorkspaceComponent": "DatabricksWorkspaceComponent"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pulumi-resource-databricks-workspace",
  "token": "pulumi:providers:pulumi-resource-databricks-workspace",
  "fqn": "pulumi_demos_pulumi_resource_databricks_workspace",
  "class": "Provider"
 }
]
"""
)
