# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = ['DatabricksWorkspaceComponentArgs', 'DatabricksWorkspaceComponent']

@pulumi.input_type
class DatabricksWorkspaceComponentArgs:
    def __init__(__self__, *,
                 location: pulumi.Input[_builtins.str],
                 spoke_cidr: pulumi.Input[_builtins.str],
                 subscription_id: pulumi.Input[_builtins.str],
                 team_name: pulumi.Input[_builtins.str],
                 cost_center: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_public_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_vnet_id: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_tier: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a DatabricksWorkspaceComponent resource.
        """
        pulumi.set(__self__, "location", location)
        pulumi.set(__self__, "spoke_cidr", spoke_cidr)
        pulumi.set(__self__, "subscription_id", subscription_id)
        pulumi.set(__self__, "team_name", team_name)
        if cost_center is not None:
            pulumi.set(__self__, "cost_center", cost_center)
        if enable_public_access is not None:
            pulumi.set(__self__, "enable_public_access", enable_public_access)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if hub_vnet_id is not None:
            pulumi.set(__self__, "hub_vnet_id", hub_vnet_id)
        if sku_tier is not None:
            pulumi.set(__self__, "sku_tier", sku_tier)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter(name="spokeCidr")
    def spoke_cidr(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "spoke_cidr")

    @spoke_cidr.setter
    def spoke_cidr(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "spoke_cidr", value)

    @_builtins.property
    @pulumi.getter(name="subscriptionId")
    def subscription_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "subscription_id")

    @subscription_id.setter
    def subscription_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "subscription_id", value)

    @_builtins.property
    @pulumi.getter(name="teamName")
    def team_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "team_name")

    @team_name.setter
    def team_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "team_name", value)

    @_builtins.property
    @pulumi.getter(name="costCenter")
    def cost_center(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "cost_center")

    @cost_center.setter
    def cost_center(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cost_center", value)

    @_builtins.property
    @pulumi.getter(name="enablePublicAccess")
    def enable_public_access(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "enable_public_access")

    @enable_public_access.setter
    def enable_public_access(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_public_access", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="hubVnetId")
    def hub_vnet_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "hub_vnet_id")

    @hub_vnet_id.setter
    def hub_vnet_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hub_vnet_id", value)

    @_builtins.property
    @pulumi.getter(name="skuTier")
    def sku_tier(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "sku_tier")

    @sku_tier.setter
    def sku_tier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "sku_tier", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("pulumi-resource-databricks-workspace:index:DatabricksWorkspaceComponent")
class DatabricksWorkspaceComponent(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cost_center: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_public_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_vnet_id: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_tier: Optional[pulumi.Input[_builtins.str]] = None,
                 spoke_cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a DatabricksWorkspaceComponent resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DatabricksWorkspaceComponentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DatabricksWorkspaceComponent resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DatabricksWorkspaceComponentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DatabricksWorkspaceComponentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cost_center: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_public_access: Optional[pulumi.Input[_builtins.bool]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 hub_vnet_id: Optional[pulumi.Input[_builtins.str]] = None,
                 location: Optional[pulumi.Input[_builtins.str]] = None,
                 sku_tier: Optional[pulumi.Input[_builtins.str]] = None,
                 spoke_cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 subscription_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 team_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DatabricksWorkspaceComponentArgs.__new__(DatabricksWorkspaceComponentArgs)

            __props__.__dict__["cost_center"] = cost_center
            __props__.__dict__["enable_public_access"] = enable_public_access
            __props__.__dict__["environment"] = environment
            __props__.__dict__["hub_vnet_id"] = hub_vnet_id
            if location is None and not opts.urn:
                raise TypeError("Missing required property 'location'")
            __props__.__dict__["location"] = location
            __props__.__dict__["sku_tier"] = sku_tier
            if spoke_cidr is None and not opts.urn:
                raise TypeError("Missing required property 'spoke_cidr'")
            __props__.__dict__["spoke_cidr"] = spoke_cidr
            if subscription_id is None and not opts.urn:
                raise TypeError("Missing required property 'subscription_id'")
            __props__.__dict__["subscription_id"] = subscription_id
            __props__.__dict__["tags"] = tags
            if team_name is None and not opts.urn:
                raise TypeError("Missing required property 'team_name'")
            __props__.__dict__["team_name"] = team_name
            __props__.__dict__["managed_resource_group_name"] = None
            __props__.__dict__["network_config"] = None
            __props__.__dict__["resource_group_name"] = None
            __props__.__dict__["workspace_id"] = None
            __props__.__dict__["workspace_url"] = None
        super(DatabricksWorkspaceComponent, __self__).__init__(
            'pulumi-resource-databricks-workspace:index:DatabricksWorkspaceComponent',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="managedResourceGroupName")
    def managed_resource_group_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "managed_resource_group_name")

    @_builtins.property
    @pulumi.getter(name="networkConfig")
    def network_config(self) -> pulumi.Output['outputs.NetworkConfig']:
        return pulumi.get(self, "network_config")

    @_builtins.property
    @pulumi.getter(name="resourceGroupName")
    def resource_group_name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "resource_group_name")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "workspace_id")

    @_builtins.property
    @pulumi.getter(name="workspaceUrl")
    def workspace_url(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "workspace_url")

