# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'NetworkConfig',
]

@pulumi.output_type
class NetworkConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "privateSubnetId":
            suggest = "private_subnet_id"
        elif key == "publicSubnetId":
            suggest = "public_subnet_id"
        elif key == "vnetId":
            suggest = "vnet_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NetworkConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NetworkConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NetworkConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 private_subnet_id: Optional[_builtins.str] = None,
                 public_subnet_id: Optional[_builtins.str] = None,
                 vnet_id: Optional[_builtins.str] = None):
        if private_subnet_id is not None:
            pulumi.set(__self__, "private_subnet_id", private_subnet_id)
        if public_subnet_id is not None:
            pulumi.set(__self__, "public_subnet_id", public_subnet_id)
        if vnet_id is not None:
            pulumi.set(__self__, "vnet_id", vnet_id)

    @_builtins.property
    @pulumi.getter(name="privateSubnetId")
    def private_subnet_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "private_subnet_id")

    @_builtins.property
    @pulumi.getter(name="publicSubnetId")
    def public_subnet_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "public_subnet_id")

    @_builtins.property
    @pulumi.getter(name="vnetId")
    def vnet_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "vnet_id")


